### ISSUE TITLE
Restfull service

### ISSUE THREAD

**Issue by aravij** [aravij/vse_svoi_restfull#1]
Create restfull service with following entities:
- User
- Community
- Wish

Relations between entities:
- User-Community: many-to-many
- User-Wish: many-to-many
- Community-Wish: one-to-many

Provide:
- [ ]  Unit and integration tests for service
- [ ]  Configuration to run service in exploring mode
- [ ] Endpoints documentation
- [ ] TS client API module
